<?php
//include('config.php');
session_start();
$firstname=$_SESSION['firstname'];
$lastname=$_SESSION['lastname'];
$username=$_SESSION['username'];
$email=$_SESSION['email'];
$password=$_SESSION['password'];
$type=$_SESSION['type'];
$otp2=$_SESSION['otp'];
?>